import { chromium } from "playwright";
import { requireEnv } from "./env.mjs";
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto(requireEnv("APP") + "/", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(4000);
const shot = "/w/shots/angular-tracker.png";
await page.screenshot({ path: shot, fullPage: true });
const text = await page.evaluate(() => document.body.innerText.slice(0, 500));
const rows = await page.locator("[data-testid=row]").count();
const backends = await page.locator("[data-testid=backend-select] option").allTextContents();
console.log("ROWS:", rows);
console.log("BACKENDS:", backends.join(","));
console.log("TEXT:", text.replace(/\n+/g, " | ").slice(0, 300));
console.log("ERRORS:", errors.slice(0, 3).join(" ~ "));
await browser.close();
