#!/usr/bin/env python3
"""Render README.md from README.in.md against stacks/manifest.yaml.

The README states ports and counts, because a README that will not tell you which URL to
open is not doing its job. Both are declared in the manifest, and a second copy of a
declared value is a copy that goes stale, so the prose carries placeholders and this
fills them in.

    {{port:angular}}          the port that stack publishes on the host
    {{port:side-by-side}}     the same, for an infrastructure service
    {{count:stacks}}          how many stacks are active
    {{count:backends}}        active stacks with role: backend
    {{count:frontends}}       active stacks with role: frontend

An unknown placeholder is an error rather than a passthrough. A typo that rendered as
itself would ship `{{prot:angular}}` into the README and read as a formatting bug rather
than as a wrong number, which is the more expensive of the two failures.

A `!` escapes one: `{{!port:angular}}` renders as the literal text `{{port:angular}}`, so
the README can show the syntax it is written in. Without it, documenting the mechanism was
the one thing the mechanism could not do.

The rendered file carries a generated banner and the host suite re-runs this script and
compares, so hand-editing README.md to say something the manifest does not is caught.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "README.in.md"
TARGET = ROOT / "README.md"

BANNER = (
    "<!-- GENERATED from README.in.md by scripts/render-readme.py. Do not edit this file;\n"
    "     edit README.in.md. Ports and counts come from stacks/manifest.yaml. -->\n"
)

PLACEHOLDER = re.compile(r"\{\{\s*(!?)(count|port):([A-Za-z0-9_-]+)\s*\}\}")


def manifest() -> dict:
    return yaml.safe_load((ROOT / "stacks" / "manifest.yaml").read_text(encoding="utf-8")) or {}


def resolve(kind: str, name: str, doc: dict) -> str:
    stacks = {k: v for k, v in (doc.get("stacks") or {}).items() if v.get("active")}
    infra = doc.get("infrastructure") or {}

    if kind == "port":
        if name in stacks and stacks[name].get("port"):
            return str(stacks[name]["port"])
        spec = infra.get(name)
        if isinstance(spec, dict) and spec.get("port"):
            return str(spec["port"])
        raise SystemExit(f"README placeholder {{{{port:{name}}}}}: no such port in the manifest")

    counts = {
        "stacks": len(stacks),
        "backends": len([s for s in stacks.values() if s.get("role") == "backend"]),
        "frontends": len([s for s in stacks.values() if s.get("role") == "frontend"]),
    }
    if name not in counts:
        raise SystemExit(
            f"README placeholder {{{{count:{name}}}}}: known counts are "
            + ", ".join(sorted(counts))
        )
    return str(counts[name])


def render() -> str:
    if not SOURCE.is_file():
        raise SystemExit(f"{SOURCE.relative_to(ROOT)} is missing; it is the README's source")
    doc = manifest()
    text = SOURCE.read_text(encoding="utf-8")

    # An escaped placeholder becomes a sentinel first and braces again last, so the
    # leftover check below still sees a genuinely unresolved one. Restoring the braces
    # before that check would make every escape look like a typo.
    escaped_marker = "\x00{}:{}\x00"

    def substitute(match: re.Match) -> str:
        escaped, kind, name = match.groups()
        if escaped:
            return escaped_marker.format(kind, name)
        return resolve(kind, name, doc)

    out = PLACEHOLDER.sub(substitute, text)

    leftover = re.search(r"\{\{[^}]*\}\}", out)
    if leftover:
        raise SystemExit(
            f"unresolved placeholder {leftover.group(0)!r} in {SOURCE.name}; the known "
            "forms are {{port:<name>}}, {{count:<set>}}, and {{!...}} for a literal"
        )

    return BANNER + "\n" + re.sub(r"\x00([a-z]+):([A-Za-z0-9_-]+)\x00", r"{{\1:\2}}", out)


def main() -> int:
    rendered = render()
    changed = not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"README.md {'rendered' if changed else 'unchanged'} from README.in.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
